version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: docker-compose-vue-app
    ports: 
      - "3030:3030"
      
  backend:
    build: ./backend
    ports:
      - "9090:9090"
    volumes:
      - /home/docker/.m2:/root/.m2
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydatabase
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - type: volume
        source: db_data
        target: /var/lib/mysql          
      - type: bind
        source: ./db/init.sql
        target: /docker-entrypoint-initdb.d/init.sql
volumes:
  db_date:
    name: db_data
